### ISSUE TITLE
Add ability to emit logs in JSON format

### ISSUE THREAD

**Issue by GiedriusS** [cortexlabs/cortex#1046]
#### Description

Add the ability to switch between log formats. I propose adding a new option `-log.format` that could either be `logfmt` (default and the current format) or `json`. These two options are what Thanos has and that model works well so I think Cortex could have a similar thing. 

#### Motivation

It would be nice to have structured logs in a strict format that other systems can effortlessly understand. The use-case is to avoid adding another parsing step on top of Cortex's logs and be able to parse JSON directly. To be even more specific, I'd like to send Cortex logs to Elasticsearch and have as few parsing steps as possible.

**Comment by deliahu** [comment]
@GiedriusS thank you for creating this ticket, and for describing your use case and motivation so clearly. This is something that we will definitely look into.

Right now, logs are sent to Cloudwatch as JSON with just a single "log" key (which contains all of the text from the log). Does the current architecture work for you, except that you would like the json to include more fields (i.e. log level, timestamp, ...), and the "log" field would contain only the actual log message? (we could also rename the "log" field to e.g. "text" if that makes more sense)

Here is a log in Cloudwatch today:

```json
{
    "log": "2020-04-03 00:19:37.667433:cortex:pid-1:INFO:pulling the python serving image"
}
```

Would you want this?

```json
{
    "timestamp": "2020-04-03 00:19:37.667433",
    "pid": 1,
    "level": "INFO",
    "log": "pulling the python serving image"
}
```

In cases where users call `print()` from their implementations, would we just leave all of the metadata fields blank and only have the single "log" key (like it is today)?

Also, would you want access to the Cortex logger so that you could log in the same JSON format? Or is there a standard format you can point us to that if we follow it, it's easy to replicate it in your predictor code?

Finally, are you able to easily ingest the json logs from CloudWatch to Elasticsearch?

**Comment by GiedriusS** [comment]
> @GiedriusS thank you for creating this ticket, and for describing your use case and motivation so clearly. This is something that we will definitely look into.
> 
> Right now, logs are sent to Cloudwatch as JSON with just a single "log" key (which contains all of the text from the log). Does the current architecture work for you, except that you would like the json to include more fields (i.e. log level, timestamp, ...), and the "log" field would contain only the actual log message? (we could also rename the "log" field to e.g. "text" if that makes more sense)
> 
> Here is a log in Cloudwatch today:
> 
> ```json
> {
>     "log": "2020-04-03 00:19:37.667433:cortex:pid-1:INFO:pulling the python serving image"
> }
> ```
> 
> Would you want this?
> 
> ```json
> {
>     "timestamp": "2020-04-03 00:19:37.667433",
>     "pid": 1,
>     "level": "INFO",
>     "log": "pulling the python serving image"
> }
> ```
> 
> In cases where users call `print()` from their implementations, would we just leave all of the metadata fields blank and only have the single "log" key (like it is today)?
> 
> Also, would you want access to the Cortex logger so that you could log in the same JSON format? Or is there a standard format you can point us to that if we follow it, it's easy to replicate it in your predictor code?
> 
> Finally, are you able to easily ingest the json logs from CloudWatch to Elasticsearch?

Oh lord, I just realized that I have opened this issue in a wrong repository. :smile: :smile: I wanted to open it up here: https://github.com/cortexproject/cortex. Please ignore this message. :smile: I clearly didn't have enough sleep yesterday.

**Comment by deliahu** [comment]
@GiedriusS No worries, I hope you caught up on sleep last night :)
