### ISSUE TITLE
When modifying the predictor (in Python), should I delete the API or re-deploy?

### ISSUE THREAD

**Issue by MrRace** [cortexlabs/cortex#1087]
when modify the python code, I want the new code works, should I reload the api and how?  Is the only way that I should detete the api, then use `cortex deploy` ? Thanks advance!

**Comment by RobertLucian** [comment]
The Cortex APIs are managed declaratively. This means that with each new modification brought to your API config (`cortex.yaml`), running `cortex deploy` will update your deployed API.

Please keep in mind that a rolling-update approach is employed with the update process of a deployed API, so if you don't have enough compute capacity around (either because you've hit the ceiling capacity of your cluster or because your local machine is close to being maxed out), then your API may never get updated - just keep that in mind.

The rolling-update strategy is used to ensure zero downtime of your service.

On the other hand, if you just want to get rid of the old API replica(s) and spawn a new one instead, just hit `cortex delete <api> && cortex deploy`. You'd probably want to go with this one when there isn't much compute capacity available (or when your API is using a substantial amount of resources relative to the cluster's capacity).

**Comment by MrRace** [comment]
Thanks for your prompt reply.  Do you mean the rolling-update strategy will keep my service accessible when run `cortex deploy`? I try it in my local machine, it seems not work as my expectation. After running `cortex deploy`,   the service is unaccessible over a period of time.
If I want to update my service hot restart(like nginx‘s `reload`’), how should I set my configuration?
Thanks a lot!

**Comment by vishalbollu** [comment]
The behaviour you encountered with `cortex deploy` on a local machine is expected because update operations on a local machine take down the previous API and then spin up the latest API. Unfortunately, rolling update strategy is only supported in cluster deploys (on AWS) and is not supported in local mode.

**Comment by deliahu** [comment]
I'll go ahead and close this issue, feel free to re-open it or create a new one if you have any more questions
