### ISSUE TITLE
Support secret key for API authorization

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#1092]
#### Description

Add an API config to specify a secret key, which must be specified in the prediction request (e.g. in the header or as a query param). If the key is not provided, the API should respond with error code 403. The value could be the key itself, or a path to an s3 object which contains the key.

This would also be applied to batch job submission.

**Comment by rdwrt** [comment]
+1 for this. Not having API authorization is a clear blocker for many deployments. 
Any projected release date for cortex with apu authorization?

**Comment by RobertLucian** [comment]
@rdwrt we're gonna assign a higher priority to this, and we'll try to implement it. Thanks for bringing this up to us!

In the meantime, it's worth mentioning that the Cortex CLI creates an HTTP API Gateway when `cluster`ing up. **One way** for you is to do the auth with JWT. More on this here:
https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-jwt-authorizer.html

**Another workaround** would be to create a REST API Gateway just like it's shown [in here (this is an old guide for 0.17 btw)](https://docs.cortex.dev/v/0.17/guides/api-gateway) and then you'd set up API keys for your paths. When an API key doesn't match what the API GW has, then it's gonna respond with error code 403. You can either import or create API keys with the AWS API Gateway. More on this here:
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-api-usage-plans.html

Also, can you tell us more about the kind of auth you'd be more interested in?

**Comment by rdwrt** [comment]
Hi Robert, I am thinking of a local setup for cortex, where something like OAuth is used to perform the authentication. It'll look something like:

![](http://blog.geveo.com/img/Tharindu1.png)

(example from just a random hit from Google: http://blog.geveo.com/OAuth-Implementation-for-WebAPI2 )

**Comment by RobertLucian** [comment]
@rdwrt got it. When you say local setup for Cortex, do you mean deploying Cortex APIs locally? (with the `-e local` option).

Regarding setting up OAuth to perform authorization, you can use AWS Cognito for that. It integrates nicely with the AWS API Gateway. It's also managed, so that's great. You can check out the following resources on this matter:
* https://stackoverflow.com/questions/32236568/how-to-set-up-an-oauth2-authentication-provider-with-aws-api-gateway
* The AWS documentation on setting up AWS Cognito for API Gateway can be found here: https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-integrate-with-cognito.html
* And a nice tutorial showing how AWS Cognito is set up can be found [here](https://medium.com/@awskarthik82/part-1-securing-aws-api-gateway-using-aws-cognito-oauth2-scopes-410e7fb4a4c0) and [here](https://medium.com/@awskarthik82/part-2-securing-aws-api-gateway-using-aws-cognito-oauth2-scopes-and-openid-connect-f20fd1392e97).

I really liked the following diagram, because it visually explains how OAuth2 authorization is performed:

![0*vXjRjS4vzOV9TFBh](https://user-images.githubusercontent.com/26958764/87085116-01a88580-c238-11ea-93ab-b13adc504847.png)

**Comment by rdwrt** [comment]
The problem is this requires AWS. How do I set this up without using AWS?

**Comment by RobertLucian** [comment]
@rdwrt if you go with a 3rd-party solution, then the common denominator is in implementing the access token validation mechanism on your Cortex API. 

In the `predict` method of your predictor class, you would first make a request to your auth server to validate your access token. If it checks out, make the prediction and return a response, otherwise, just return 403 in case the token is invalid or 401 if it's not present. You do this by returning a [starlette.responses.Response](https://www.starlette.io/responses/) object in your `predict` method.

The only downside to this is that you have to initiate the validation process directly on your resource server (your Cortex APIs) as opposed to doing it before that like it's the case with Amazon Cognito.

Your auth server is responsible for issuing you an access token (+ optional refresh token) if your authorization code checks you, and then you embed the access token in your request to your resource server (Cortex API).

There are multiple OAuth providers. 2 that I can think of are:
* https://auth0.com
* And Okta. Check this out: https://developer.okta.com/code/python/.

> There are valid reasons not to use AWS for this (existing contracts, funding for a specific cloud provider, company policies, existing on-premise infrastructure, etcetera)

Then it really depends on what your existing infrastructure already looks like. How is your authentication/authorization infrastructure configured?

**Comment by deliahu** [comment]
I'll go ahead and close this issue, since this can be easily implemented by adding the secret key to the `config` field of the predictor, and then checking a header / query param / body field for the secret key in `predict()`
