### ISSUE TITLE
Build python-predictor-cpu by myself can not run the container

### ISSUE THREAD

**Issue by MrRace** [cortexlabs/cortex#1093]
I had builded `python-predictor-cpu`  with the dockerfile in `https://github.com/cortexlabs/cortex/tree/master/images/python-predictor-cpu`.  And it seems Successfully!
![image](https://user-images.githubusercontent.com/10300313/83325732-3c1a1c80-a2a1-11ea-99bb-d4800a709f18.png)

But when to run a container based the new image(`docker run -it --name=ljp_test  ljp/cortex-python-predictor-cpu:latest bash`), it failed. The message is below:
```
/src/cortex/serve/run.sh: line 22: cd: /mnt/project: No such file or directory
```
And I check the `run.sh` and other files,  can not find where to new the directory. Even try to run container base the Image `cortexlabs/python-predictor-cpu-slim:0.17.0` and `cortexlabs/python-predictor-cpu:0.17.0` come the same error, and can not setup the container. Why and How?

**Comment by deliahu** [comment]
@MrRace The cortex docker images are designed only to be used through the cortex CLI, so that cortex can help with some additional tasks. You can put your [Predictor implementation](https://docs.cortex.dev/deployments/predictors) in a directory, then add a `cortex.yaml` file which contains the [API configuration](https://docs.cortex.dev/deployments/api-configuration#python-predictor) for your API (including the path to the docker image that you built), and then run `cortex deploy`. Here is a [tutorial](https://docs.cortex.dev/iris-classifier).

**Comment by deliahu** [comment]
I'll go ahead and close this issue, feel free to re-open it or create a new one if you have any more questions
