### ISSUE TITLE
About Cloud Provider 

### ISSUE THREAD

**Issue by zouyee** [cortexlabs/cortex#1129]
Do we want to support different clouds or remain dependent on aws, and whether we plan to support multiple container orchestration system?

**Comment by zouyee** [comment]
Currently the code shows tight coupling to aws ❤️

**Comment by deliahu** [comment]
@zouyee Yes, there is currently tight coupling to aws. This is because in order to implement some of our features, like spot instances, we had to use many aws-specific tools. Adding support for additional cloud providers is something we will eventually want to do, but is not on our immediate roadmap because it will be a large effort. We have GitHub issues for supporting [GCP](https://github.com/cortexlabs/cortex/issues/114), [Azure](https://github.com/cortexlabs/cortex/issues/811), and [on-premise](https://github.com/cortexlabs/cortex/issues/150).

**Comment by deliahu** [comment]
I'll close this issue now, feel free to reach out if you have additional questions about this
