### ISSUE TITLE
Using a different Python version in the context of custom-built images

### ISSUE THREAD

**Issue by MrRace** [cortexlabs/cortex#1143]
My dockerfile：
```
FROM cortexlabs/python-predictor-cpu-slim:0.17.0
RUN apt-get update \
    && apt-get install -y tree \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /etc/pip/requirements.txt
# /bin/bash is required

RUN /bin/bash -c "pip install --no-cache-dir --trusted-host mirrors.aliyun.com -i http://mirrors.aliyun.com/pypi/simple/ -r /etc/pip/requirements.txt "
```
I build my own Image based on `cortexlabs/python-predictor-cpu-slim:0.17.0`, however the python version is 3.6.9, I want to update the python version to python 3.8, How to modify my  dockerfile above?
Thanks a lot!

**Comment by RobertLucian** [comment]
@MrRace to do this in a Dockerfile, as opposed to changing the Python version by dropping a different in a [`conda-packages.txt`](https://docs.cortex.dev/deployments/python-packages#conda-packages), you can do it like in the following:

```Dockerfile
FROM cortexlabs/python-predictor-cpu-slim:0.17.0

# to install the new Python version
# pip packages have to be reinstalled for the new version
RUN pip uninstall -yr  /src/cortex/serve/requirements.txt && \
    conda install -y conda-forge::python=3.8 && \
    conda clean -a && \
    pip --no-cache-dir install -r /src/cortex/serve/requirements.txt

# you now have Python 3.8 installed at this point
# your stuff here
```

Just keep in mind that the Cortex team cannot guarantee the stability of the system when a different version of Python is used - the reason is that we haven't tested it against other versions.

**Comment by deliahu** [comment]
I'll close this ticket now, feel free to reach out if you have additional questions
