### ISSUE TITLE
Max number of multiple requests at a time 

### ISSUE THREAD

**Issue by MrRace** [cortexlabs/cortex#1148]
In `cortex.yaml` I set:
```
  compute:
    cpu: 50
```
I deploy my model in my local machine. Is that mean the max number of multiple requests to make at a time is just 50？If more than 50 requests at a time, the requests must wait for the server?  What should I do, if I want to process more requests at a time？ Thanks a lot!

**Comment by deliahu** [comment]
`cpu: 50` configures how much CPU to allocate to each replica of the API. Since you are running locally, there will only be one replica, and the actual CPU available will be less (it will be limited by your machine and Docker configuration). The amount of CPU allocated does not affect the concurrency of the API.

Concurrent requests are not currently supported for local deployment (here is the issue we have to add it: https://github.com/cortexlabs/cortex/issues/960). It is supported on AWS, via `workers_per_replica` and `threads_per_worker` in the `autoscaling` field (see [here](https://docs.cortex.dev/deployments/autoscaling#replica-parallelism)).

**Comment by MrRace** [comment]
@deliahu Looking forward to  concurrent requests  for local deployment!  Next version？

**Comment by RobertLucian** [comment]
@MrRace as far as I am aware, this is gonna land in `0.19`.

**Comment by MrRace** [comment]
@RobertLucian  Do you have any advise for concurrent requests in local deployment current? It is a immediate emergency, I can not just wait.........

**Comment by RobertLucian** [comment]
@MrRace I see. In this case, knowing it's an urgency for you, we can assign a higher priority to this ticket and try to get it into 0.18. We are planning to cut the 0.18 release candidate tomorrow, so we can't make any promises that this will make it in.

**Comment by RobertLucian** [comment]
@MrRace I have great news for you. The option to set concurrency fields for local deployments is going to be possible with `0.18`. This feature is enabled by https://github.com/cortexlabs/cortex/pull/1158.

**Comment by deliahu** [comment]
Thanks @RobertLucian for your quick turnaround on this!

**Comment by deliahu** [comment]
This has now been released in v0.18.0

**Comment by MrRace** [comment]
@deliahu @RobertLucian  Great!  Thanks a lot! Can't wait to try!
