### ISSUE TITLE
Increase instances in a cluster

### ISSUE THREAD

**Issue by francis967** [cortexlabs/cortex#1381]
Hi everyone,

Is it possible to increase the number of instances of a cluster already running, without having to turn off the cluster?
and if so, how?

My intention is to be able to increase the number of machines in the cluster as I need more computing capacity, without having to lose the models already deployed.

Thanks in advance

**Comment by RobertLucian** [comment]
@francis967 I suppose you are referring to the `max_instances` field available in `cluster.yaml` config (or as provided to `cortex cluster up` via the prompt if run without a config). The `max_instances` field is documented [here](https://docs.cortex.dev/cluster-management/config).

> Is it possible to increase the number of instances of a cluster already running, without having to turn off the cluster?
and if so, how?

> My intention is to be able to increase the number of machines in the cluster as I need more computing capacity, without having to lose the models already deployed.

Yes, that is possible. You just need to use the `cortex cluster configure` command to do that. If using a `cluster.yaml` config, then update the `max_instances` field to the higher value and then run `cortex cluster configure -c cluster.yaml`. Otherwise, use the CLI's prompt to update the value (by not running it with the `-c` option).

**Comment by francis967** [comment]
Great, that worked perfectly, it was exactly what i was looking for.

Thanks @RobertLucian , and thank you for such a great tool

**Comment by RobertLucian** [comment]
Happy to hear that! Thanks! I'm gonna close this now.
