### ISSUE TITLE
Per Process GPU Ram

### ISSUE THREAD

**Issue by AkashDharani** [cortexlabs/cortex#1426]
As you have mentioned in docs gpus.md about the limiting the gpu ram, I know what exactly code snippet I have to use, but dont know exactly where I have to write that code snippet in cortex source code.

`mem_limit_mb = 1024
for gpu in tf.config.list_physical_devices("GPU"):
    tf.config.set_logical_device_configuration(
        gpu, [tf.config.LogicalDeviceConfiguration(memory_limit=mem_limit_mb)])`

**Comment by RobertLucian** [comment]
@AkashDharani this has to be done in the predictor's constructor. It should follow this pattern:

https://github.com/cortexlabs/cortex/blob/889627755582365123f086c673466aa7bcbcc574/examples/tensorflow/license-plate-reader/predictor_crnn.py#L11-L19

Likewise for your specific code snippet. It will take the same place in the predictor's constructor.

**Comment by AkashDharani** [comment]
GPU is not available in this class, tf.test.is_gpu_available() is giving false in the constructor of tensorflow predictor class. But tensorflow_model_server is loaded in my gpu memory and occupying full gpu ram.

**Comment by RobertLucian** [comment]
@AkashDharani the `tensorflow_model_server`? Are you using the `TensorFlowPredictor` predictor? In either case, could we see the predictor's implementation? And is this run locally?

**Comment by AkashDharani** [comment]
Yes I am using the `TensorFlowPredictor` predictor, and I am running it locally on RTX-2080 Ti. When I import tensorflow in `TensorflowPredictor` and test the availability of gpu it returns False `tf.test.is_gpu_available()`. But the models is getting loaded in gpu ram, it is occupying whole gpu ram.

**Comment by RobertLucian** [comment]
@AkashDharani when using the TensorFlow predictor, you only have to provide the model(s) to the predictor via the `cortex.yaml` config file. All the rest is handled by Cortex already. And since this is running a TFS server, loading a model into the GPU's memory will only use as much memory as it needs.

The suggestions mentioned in https://docs.cortex.dev/advanced/gpus#tips are for when the `PythonPredictor` predictor is used. It doesn't apply to the `TensorFlowPredictor` predictor.

You can check out [this example](https://github.com/cortexlabs/cortex/tree/master/examples/tensorflow/multi-model-classifier) that loads multiple models into the memory while using the `TensorFlowPredictor` predictor.

**Comment by deliahu** [comment]
@AkashDharani I would also like to add: if you would prefer to implement your inference in Python rather than using the `TensorFlowPredictor` type (which automatically loads your SavedModel into a sidecar TF Serving container), you can use the `PythonPredictor` predictor type ([docs](https://docs.cortex.dev/deployments/realtime-api/predictors#python-predictor)), which will give you access to a Python environment with the GPU available.

**Comment by AkashDharani** [comment]
@deliahu Thanks for your advice, will try PythonPredictor.
@RobertLucian It is accessing full gpu ram while using TensorflowPredictor instead of what model needs. I have also used tensorflow-serving docker image separately and deployed models, it also acquire full gpu ram which i limited by giving a parameter --per_process_gpu_memory_fraction.

**Comment by RobertLucian** [comment]
@AkashDharani in that case, you could add in the `--per_process_gpu_memory_fraction` flag to [run.sh](https://github.com/cortexlabs/cortex/blob/0.20/images/tensorflow-serving-gpu/run.sh#L31), which is the entry-point that is run when the TFS server is brought up. The associated Dockerfile for the TFS for the GPU is [this one](https://github.com/cortexlabs/cortex/blob/0.20/images/tensorflow-serving-gpu/Dockerfile) (which is residing in the same directory as `run.sh`). For building this image, make sure you do this from the root directory of the repo.

Once your custom image is built, add it to the `tensorflow_serving_image` field in your API's `cortex.yaml` config:
```yaml
- name: <your-API>
  kind: RealtimeAPI
  predictor:
    type: tensorflow
    # ...
    tensorflow_serving_image: <string> # docker image to use for the TensorFlow Serving container (default: cortexlabs/tensorflow-serving-gpu or cortexlabs/tensorflow-serving-cpu based on compute)
    # ...
```

For a bit more context, all of the available flags that can be passed to `tensorflow_model_server` are documented here https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/main.cc#L59.

I haven't tried this, but I reckon this would work. I'm curious to see if it limits the memory usage on the GPU. Please, let us know.

**Comment by RobertLucian** [comment]
@AkashDharani I confirm the following two things:

1. That indeed the TFS server reserves all of the GPU's memory.
1. That passing the `--per_process_gpu_memory_fraction` inside the indicated `run.sh` script does indeed limit the memory usage.

I've tried this using the [iris-classifier](https://github.com/cortexlabs/cortex/tree/master/examples/tensorflow/iris-classifier).

**Comment by deliahu** [comment]
@AkashDharani were you able to get one of the two approaches we mentioned working?

**Comment by AkashDharani** [comment]
@deliahu Yes, I have already worked on tensorflow/serving, it does work and in cortex dev `--per_process_gpu_memory_fraction` is also working, but I am trying to adjust this functionality in `cortex.yaml` file.

**Comment by AkashDharani** [comment]
@RobertLucian  where exactly cortex.yaml file is getting read and loaded into api variable in go files, because I am facing error while reading `gpu: 0.25`, it is not supported `compute: key "gpu" is not supported` 
I want to update the `cortex.yaml` file and go files which are loading` cortex.yaml` file into api variable as well.

**Comment by RobertLucian** [comment]
@AkashDharani when you do `cortex deploy`, it looks in the current directory and checks if there's a config called `cortex.yaml`. Otherwise, if you manually specify a config like `cortex deploy this_config.yaml`, then this `this_config.yaml` config will still have to be found in the same directory from which the CLI command is run.

The `cortex.yaml` config template for each predictor type can be found [here](https://docs.cortex.dev/deployments/realtime-api/api-configuration).

Aside from the error you are currently getting, for the `compute.gpu` field you can only assign integer values. Fractional values are not yet handled. We have a ticket for it to track it https://github.com/cortexlabs/cortex/issues/1390.

And also, to speed up the process, in case you didn't get it to work, could you also post your `cortex.yaml` API config here?

**Comment by AkashDharani** [comment]
@RobertLucian I got your point, but as I am building the cortex from source, so I can change the source code and make able the cortex to work with float values in `compute.gpu` as well, thats what I was asking, can you exactly tell me the name of the file where `cortex.yaml` is getting loaded into our code so that I can remove this exception from `compute.gpu` of being integer.

**Comment by RobertLucian** [comment]
@AkashDharani I see. In that case, you'd probably want to change this to a float.

https://github.com/cortexlabs/cortex/blob/c6a3894009dae55de5cec68deb97c7d832514da0/pkg/types/spec/validations.go#L339-L345

**Comment by AkashDharani** [comment]
@RobertLucian I am facing this gpu ram issue while deploying the model in cluster on ec2 instance. Locally it is acquiring only 0.25 percent of ram but on ec2 instance it acquires whole available ram.

https://github.com/cortexlabs/cortex/blob/c6a3894009dae55de5cec68deb97c7d832514da0/cli/local/docker_spec.go#L337-L340

updated it to

`
	cmdArgs := []string{
		"--port=" + _tfServingPortStr,
		"--per_process_gpu_memory_fraction=0.25",
		"--model_config_file=" + _tfServingEmptyModelConfig,
	}

`
But it is effecting the local deployment not on cloud deployment.

**Comment by RobertLucian** [comment]
@AkashDharani I see what you want to do - basically you don't want `compute.gpu` to take fractional values (as in it's okay if it takes integers), but you want the GPU's memory to not get fully occupied when a model is loaded. For that, you'll have to add that `--per_process_gpu_memory_fraction` option right in here https://github.com/cortexlabs/cortex/blob/master/pkg/operator/operator/k8s.go#L668.

But keep in mind that for AWS deployments, even though a GPU's memory is not fully utilized, that GPU unit will still be allocated to a single API replica - meaning that the rest of the GPU's available memory can't be shared with other replicas.

For that, a device plugin that supports fractional values for the GPU is required - as far as we know, the official device plugin for the Nvidia GPUs doesn't support that, but there may be 3rd party ones that do this - you can check out the links from the ticket's description in here https://github.com/cortexlabs/cortex/issues/1390.

**Comment by AkashDharani** [comment]
@RobertLucian Thank you, now gpu memory is not fully utilized on instance as well, but can't deploy more than one model in same ec2 instance, working on it, if I can find any way out.

There is another issue I am facing is FPS issue, locally a model gives around 100 FPS with cortex but while deploying that same model using cortex in us-east-1 in aws env and hitting that model from us-east-1 gives around 30 fps.

**Comment by RobertLucian** [comment]
> Thank you, now gpu memory is not fully utilized on instance as well, but can't deploy more than one model in same ec2 instance, working on it, if I can find any way out.

Yes, that's definitely the issue we are tracking here https://github.com/cortexlabs/cortex/issues/1390. By more than one model, I take you are referring to having multiple pods (on the same instance) having access to the same GPU unit. The official device plugin from Nvidia can't split the GPU to different pods. A 3rd-party one may be required. Looking to see if you find a way around this.

> There is another issue I am facing is FPS issue, locally a model gives around 100 FPS with cortex but while deploying that same model using cortex in us-east-1 in aws env and hitting that model from us-east-1 gives around 30 fps.

If it's the same GPU and there's no bottleneck on your dev box (internet connection, compute capacity) and the model is also loaded on the GPU's memory, then this shouldn't happen at all. The performance should be the same. Also, by FPS I suppose you mean the number of inferences per second.

Looking forward to hearing more about this.

**Comment by RobertLucian** [comment]
@AkashDharani 

Thought about this for a bit and I have 2 more questions for you:
1. Are you just looking to load multiple models on the same API? Because we already support that for the TensorFlow and ONNX predictors [here](https://docs.cortex.dev/guides/multi-model#tensorflow-predictor). We are also currently working on https://github.com/cortexlabs/cortex/pull/1428 which will give you more granular control over your deployed models.
1. Do you want to load the same model multiple times on the same API replica? If so, then just setting `processes_per_replica` to anything greater than 1 will do the job.

Waiting for feedback from you.

**Comment by AkashDharani** [comment]
@RobertLucian there isn't any bottleneck one dev box, in internet both client and server are in aws ec2 instances and compute capacity is also not an issue. and yes FPS mean the number of inferences per second.

1. I am only deploying one model in one ec2 instance for now to compute inferences per second, not using multi-model deployment for now.
2. I will use `process_per_replica` in future, but for now I just want to know the capacity of single model locally, on ec2 and their difference.

**Comment by AkashDharani** [comment]
@RobertLucian I have calculated FPS in predictor file as well to get idea if there is any issue with model compute, but FPS is fine in predictor no loss, it means there isn't any issue with compute. Network can't be issue as well because both client and sever are on aws in same region.

**Comment by RobertLucian** [comment]
@AkashDharani closing this one as we already have https://github.com/cortexlabs/cortex/issues/1440. Thanks!
