### ISSUE TITLE
How fast can Cortex spin down spot instances?

### ISSUE THREAD

**Issue by da-source** [cortexlabs/cortex#1462]
I have a quite large image recognition model that needs one whole AWS EC2 instance to run. Model runs only for about 2-3 minutes after which, there is no use for it and it needs to be spun down. I'm wondering: how long does it take for cortex to automatically spin down unused instance? Is it immediatly or does it take a few minutes ? (I dont want the instance to run longer than it has to)

**Comment by deliahu** [comment]
@da-source Without having the full context of your application, to me this seems like a good use case for a [batch API](https://docs.cortex.dev/deployments/batch-api) (instead of a realtime API), since with batch APIs in cortex, no instances are required until a request comes in, and the instance(s) spin down after the job is completed. There will still be a delay of a few minutes for the instance to spin down.
