### ISSUE TITLE
Create Websocket on AWS EC2 instance using cortex

### ISSUE THREAD

**Issue by mutal** [cortexlabs/cortex#1506]
I would like to create websockets on the instances that Cortex automatically spins up. A user mentioned that Cortex doesn’t yet support sockets. I figure that, AWS EC2 instances that cortex spins up run on Linux machines and that they should be able to run as websocket servers. Is this correct?

**Comment by mutal** [comment]
> I would like to create websockets on the instances that Cortex automatically spins up. A user mentioned that Cortex doesn’t yet support sockets. I figure that, AWS EC2 instances that cortex spins up run on Linux machines and that they should be able to run as websocket servers. Is this correct?

Let's say in my `predictor.py`s ` init ` function I would create a websocket and populate it with my model. I then could pass websocket's credentials to the client side and which then could communicate with the websocket server. Once the user completes the process client side could notify the Cortex API instance that it is over and Cortex would then spin it down. Could this be done?

**Comment by deliahu** [comment]
Yes, this makes sense, thanks for your suggestion. I have created this ticket (https://github.com/cortexlabs/cortex/issues/1508) to track the feature.

**Comment by mutal** [comment]
> Yes, this makes sense, thanks for your suggestion. I have created this ticket (#1508) to track the feature.

sorry for being intrusive, but how is progress going on that ticket?

**Comment by deliahu** [comment]
Thanks for following up. We have not yet made progress on #1508, and haven't decided yet on how to prioritize it compared to our other tickets.

**Comment by mutal** [comment]
I see. What is the usual time for Cortex feature to be implemented after
it’s been announced? (This ticket was opened about 3 weeks ago)

**Comment by deliahu** [comment]
@mutal we use github issues as a list of features that we can potentially work on next. Once we decide to prioritize it for a particular release, we'll add a label marking the release we're targeting. Once we start working on it, we'll move it to "In progress" in the GitHub project. Since https://github.com/cortexlabs/cortex/issues/1508 has not been labeled with a release tag and is still in the "To prioritize" category in the GitHub project, that means that we have not yet decided when we will start working on this feature. Every two weeks we look at the "To prioritize" list and decide what to work on next. There are many features in the "To prioritize" list, and currently there are a few I can think of that we will probably prioritize higher than https://github.com/cortexlabs/cortex/issues/1508, like GCP support (although this is a team decision, not just mine).

**Comment by mutal** [comment]
Oh, I see. Would it be reasonable to expect #1508 to be resolved before
January?

**Comment by deliahu** [comment]
@mutal at this point, we aren't able to predict; we usually prioritize 2-3 weeks an advance, so we'd probably have a clearer picture in a few weeks.

**Comment by mutal** [comment]
I would be really grateful if you could try prioritizing this issue. I’m
working on project with a group and websockets are a key element in our
platform and we would really like to use Cortex in our implementation
instead of developing a whole new scalable infrastructure system. Hope you
understand. I’ll be waiting.

**Comment by deliahu** [comment]
@mutal I understand, thanks for explaining. That said, we still cannot commit to supporting this yet. It might be best to try to get it working using the current architecture; this should be possible to do (possibly with a minor modification to your inference program). My understanding is that right now, you send the input text to your program, and then the result is printed out as it's generated. Is it instead possible to implement your inference program so that when you run `./mycommand`, the program doesn't exit, and instead accepts text input on stdin? If so, I think we can make it work in the current architecture.

**Comment by mutal** [comment]
Unfortunately the program that I use doesn’t have that functionality.
Perhaps it is possible to manually implement a websocket within a current
architecture?

**Comment by deliahu** [comment]
@mutal I have responded on https://github.com/cortexlabs/cortex/issues/1500
