### ISSUE TITLE
Dynamically update webpage using Cortex

### ISSUE THREAD

**Issue by da-source** [cortexlabs/cortex#1517]
I have a python code that runs and logs output in realtime. I would like to print that output to an HTML webpage by dynamically updating it without the page having to reload. Can this be accomplished with Cortex or will I have to use something like Flask?

**Comment by da-source** [comment]
I have a python code that runs and logs output in realtime. I would like to print that output to an HTML webpage by dynamically updating it without it having to reload. Can this be accomplished with Cortex or will I have to use something like Flask?

**Comment by da-source** [comment]
Let's say my predictor.py is like this:

import time
def predict(self, payload, query_params, headers):
        for i in range(100):
           print(i)
           time.sleep(3)

**Comment by caleb-kaiser** [comment]
Cortex Predictors are deployed as REST APIs (under the hood, Cortex uses FastAPI instead of Flask), meaning you can query them from your frontend the same way you would any other web service. In your specific example, you could use [Fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) to grab information from your endpoint, and then update the page.

To get a better sense of how Cortex deployments work, I'd recommend going through our tutorial: https://docs.cortex.dev/v/0.21/deployments/realtime-api/text-generator

**Comment by da-source** [comment]
> Cortex Predictors are deployed as REST APIs (under the hood, Cortex uses FastAPI instead of Flask), meaning you can query them from your frontend the same way you would any other web service. In your specific example, you could use [Fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) to grab information from your endpoint, and then update the page.
> 
> To get a better sense of how Cortex deployments work, I'd recommend going through our tutorial: https://docs.cortex.dev/v/0.21/deployments/realtime-api/text-generator

Could clarify how to call Fetch on an endpoint? Also is there a need to use websockets in this case to stream the data?

**Comment by RobertLucian** [comment]
@da-source you would do it like in this example (give or take):

```javascript
// Example POST method implementation:
async function postData(url = '', data = {}) {
  // Default options are marked with *
  const response = await fetch(url, {
    method: 'POST', // *GET, POST, PUT, DELETE, etc.
    mode: 'cors', // no-cors, *cors, same-origin
    cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
    credentials: 'same-origin', // include, *same-origin, omit
    headers: {
      'Content-Type': 'application/json'
      // 'Content-Type': 'application/x-www-form-urlencoded',
    },
    redirect: 'follow', // manual, *follow, error
    referrerPolicy: 'no-referrer', // no-referrer, *no-referrer-when-downgrade, origin, origin-when-cross-origin, same-origin, strict-origin, strict-origin-when-cross-origin, unsafe-url
    body: JSON.stringify(data) // body data type must match "Content-Type" header
  });
  return response.json(); // parses JSON response into native JavaScript objects
}
```

This one above is from https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch.

Here's a list of examples of API requests using the curl utility:
https://docs.cortex.dev/deployments/realtime-api/predictors#api-requests

**Comment by da-source** [comment]
> @da-source you would do it like in this example (give or take):
> 
> ```js
> // Example POST method implementation:
> async function postData(url = '', data = {}) {
>   // Default options are marked with *
>   const response = await fetch(url, {
>     method: 'POST', // *GET, POST, PUT, DELETE, etc.
>     mode: 'cors', // no-cors, *cors, same-origin
>     cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
>     credentials: 'same-origin', // include, *same-origin, omit
>     headers: {
>       'Content-Type': 'application/json'
>       // 'Content-Type': 'application/x-www-form-urlencoded',
>     },
>     redirect: 'follow', // manual, *follow, error
>     referrerPolicy: 'no-referrer', // no-referrer, *no-referrer-when-downgrade, origin, origin-when-cross-origin, same-origin, strict-origin, strict-origin-when-cross-origin, unsafe-url
>     body: JSON.stringify(data) // body data type must match "Content-Type" header
>   });
>   return response.json(); // parses JSON response into native JavaScript objects
> }
> ```
> 
> This one above is from https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch.
> 
> Here's a list of examples of API requests using the curl utility:
> https://docs.cortex.dev/deployments/realtime-api/predictors#api-requests

My predictor doesn’t exactly return anything, it rather prints out the output every 3 secs. Will that be a problem since all the predictor examples I’ve seen return something and don’t display realtime output?

**Comment by RobertLucian** [comment]
@da-source the output you are referring to is only there for debugging purposes and making sure the API is running. Your `predict` method has to return something, which will then be a part of the response payload. Here's a list of return examples:
https://docs.cortex.dev/deployments/realtime-api/predictors#api-responses

Also, to make sure this is all clear, when you say
```python
import time
def predict():
      for i in range(100):
         print(i)
         time.sleep(3)
```

I take you were referring to something like:
```python
import time

class PythonPredictor:
    def __init__(self, config):
        # your init stuff

    def predict(self, payload):
       for i in range(3):
         # your operations/predictions here

        return myresult
```

Even more so, I would advise against the use of `time.sleep`s because that will only eat into your throughput and latency.

I think our documentation might need improvement. Was there anything that was confusing with regards to the documentation? Your feedback is important.
