### ISSUE TITLE
Operator node instance type

### ISSUE THREAD

**Issue by MDLGH48** [cortexlabs/cortex#1716]
Hey all, really appreciate the work you guys are doing... quick question - is it possible to change the operator node instance type to save money?

**Comment by deliahu** [comment]
@MDLGH48 Thanks for the kind words. It is not possible to run the operator on a smaller instance type, since there are multiple services that run on the instance, which in aggregate require >2 GB of memory.

In case it's relevant, here is a guide that we created for [keeping cluster costs down](https://docs.cortex.dev/v/0.23/guides/low-cost-clusters). Let us know if you have any questions!

**Comment by deliahu** [comment]
@MDLGH48 I'll go ahead and close this issue, let us know if you have additional questions.
