### ISSUE TITLE
Increase the max length of API name

### ISSUE THREAD

**Issue by jackmpcollins** [cortexlabs/cortex#1821]
### Description

Currently, API name has a maximum length of 42 characters. I would like this to be increased to at least 100.

### Motivation

I would like to name my apis with the format `<predictor-type>/<group-id>/<individual-id>` where the ids are 36-character UUIDs.

In cortex `0.26.0`, attempting to create an api with a name of this format causes an error:
```
$ cortex deploy test.yml
error: test.yml: models/6081b22a-f92e-4a65-a18c-bb5c0b922356/3ced2176-469d-47e9-aad0-8ba33eeef216 (RealtimeAPI): name: "models/6081b22a-f92e-4a65-a18c-bb5c0b922356/3ced2176-469d-47e9-aad0-8ba33eeef216" must be no more than 42 characters

api configuration schema can be found at https://docs.cortex.dev/v/0.26/
```

### Additional context

Kubernetes limit for names for most resources is 253 characters: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/

**Comment by deliahu** [comment]
@jackmpcollins We could probably make it a little bit higher, but not a lot more, since both service names and pods names are capped at 63 characters. We arrived at 42 because, according to a comment I added a while back, k8s added 21 characters to the pod name, which contains the API name (63-21=42). We could definitely make it a little bigger (k8s seems to truncate the pod name in a deployment if necessary to make room for the IDs it adds on to the deployment name to form the pod name), and when I just checked now it seems like actually only 19 characters are added (4 of which are coming from Cortex itself, since we prefix it with `api-` which we could probably avoid if necessary), but 63 would still be the hard upper limit best-case.

Let us know if that would move the needle for you and we could research if we could increase it to 63 (or less, but still more than 42).

**Comment by jackmpcollins** [comment]
Thank you for the quick and detailed response! For our particular use-case it is actually just the endpoint that needs to have this format - which I have just discovered can be specified in the configuration yaml file for each api independently of its name. This works perfectly for us.
