### ISSUE TITLE
Is it possible to control the python version running on the cluster?

### ISSUE THREAD

**Issue by nirbd** [cortexlabs/cortex#1832]
My predictor requires python 3.8.5 and cortex server seem to have 3.6

Is it possible to control the python version ?
10X

**Comment by deliahu** [comment]
@nirbd Yes, it is possible ot change the Python version. I'd recommend building your own Docker image if possible, since otherwise it would re-install Python every time each API replica initialized (this is possible; if you'd like to go with this approach to avoid building your own image, let me know and I can send the steps).

See the guide for [creating a custom image](https://docs.cortex.dev/workloads/managing-dependencies/images). In your `Dockerfile`, you would have something like this:

```Dockerfile
FROM quay.io/cortexlabs/python-predictor-cpu-slim:0.27.0  # use gpu-slim if you're running on GPUs

# update python runtime version
RUN conda install conda-forge::python=3.8
# and reinstall core cortex runtime dependencies
RUN pip --no-cache-dir install \
    -r /src/cortex/serve/serve.requirements.txt \
    /src/cortex/serve/
```

We recently realized that this is not well-documented and could be a smoother process, so we created https://github.com/cortexlabs/cortex/issues/1779 to improve this, and plan on addressing it in the next week or two!

**Comment by deliahu** [comment]
@nirbd We have now updated the docs and added a helper script in v0.29 to make this process smoother (you can update the Python version via `dependencies.sh` ([docs](https://www.docs.cortex.dev/workloads/dependencies/system-packages)) or custom Docker images ([docs](https://www.docs.cortex.dev/workloads/dependencies/images)).

Thanks for flagging this!

**Comment by nirbd** [comment]
Awesome. thanks
