### ISSUE TITLE
I have Spot Instance Limit of 500, but can't set max_instances to 500

### ISSUE THREAD

**Issue by imagine3D-ai** [cortexlabs/cortex#1878]
I plan to use about 500 `m5.large` AWS Spot Instances and I currently have Spot Limit of 500, but when specifying `max_instances` to be 500 and trying to launch the cluster, I get:

`error: cluster.yaml: instance_type: your cluster may require up to 500 spot m5.large instances, but your AWS quota for spot m5.large instances in us-east-2 is only 500 vCPU (there are 2 vCPUs per m5.large instance); please reduce the maximum number of spot m5.large instances your cluster may use (e.g. by changing max_instances and/or spot_config if applicable), or request a quota increase to at least 1000 vCPU here: https://us-east-2.console.aws.amazon.com/servicequotas/home?region=us-east-2#!/services/ec2/quotas/L-34B43A08 (if your request was recently approved, please allow ~30 minutes for AWS to reflect this change)`

I don't plan on using multiple vCPUs of `m5.large` and will be utilizing only 1 vCPU of each instance, I willl however need to use complete memory capacity of `m5.large`. Is there a way to launch a cluster and make it fully utilize current Spot Limit, considering that I will use only 1vCPU of each instance?

**Comment by miguelvr** [comment]
1 m5.large instance has 2 vCPUs, if you use them fully or not, it's up to you. This error is from your AWS account. Basically what it says is that you do not have permission (quota) to launch more than 500 vCPUs. Since 500 m5.large = 1000 vCPUs, it raises an error.

There are 2 solutions:
1. Increase the vCPU quota on your AWS account
2. Change instance type to something that has 1 vCPU (not sure if this fits your use case, with a lot of memory)
