### ISSUE TITLE
Auto Scaling Limit Increase?

### ISSUE THREAD

**Issue by da-source** [cortexlabs/cortex#1901]
I’m preparing to launch an application and I have a current Spot Instance limit of 5000 vCPU. I was going through my AWS EC2 Limits and noticed that my Auto-Scaling groups and Launch Configurations limits are at 200. When deploying a Cortex cluster with 5000 instances, I don’t get any notifications about those particular limits, so I’m wondering if it is neccessary to request limit increases? Would it be okay to launch an application, where expected number of instances utilized will be 4000-5000 when the Auto-Scaling Group limit is at 200?

**Comment by deliahu** [comment]
@da-source those limits should not be a problem, since there will only be up to 3 Auto Scaling Groups and Launch Configurations per Cortex cluster, regardless of the number of instances in the cluster.

Also, I wanted to make sure that you are aware that the 5000 vCPU limit is regardless of the number of instances; in fact, at this scale, I'd recommend going with large instances, e.g. `m5.24xlarge` (or similar, depending on your use case). With this instance type, your cluster will have fewer instances, which means less overhead and less stress on the control plane. Keep us posted on how you decide to set it up, and how it goes for you; this sounds like a super interesting use case! What is the nature of your application?

**Comment by da-source** [comment]
@deliahu Alright, I’ll keep that in mind! I just need to provide a number of users with an option to run image classification ML inference online. I’ll keep you posted!
