### ISSUE TITLE
Prometheus Configuration in Version 0.42

### ISSUE THREAD

**Issue by 17Ants** [cortexlabs/cortex#2435]
Hi,
 We have recently migrated from version 0.35 to 0.42 and have observed that the Prometheus config has changed. We are no longer getting metrics such as kube_pod_status_phase etc. Although the default grafana dashboards show the stats, we had a lot of monitoring setup through remote write to a central Prometheus instance. This monitoring is now broken for newer clusters as the the metrics are not exposed via prometheus. Before I start fiddling around the Prometheus crds and operator, can you please tell me if things have changed and how can I have 0.35 level metrics?

Thanks in advance.

**Comment by deliahu** [comment]
Yes, you will have to fiddle around with the Prometheus crds and operator. We dropped all metrics which we weren’t showing in the default dashboards by default because the volume of metrics was causing issues in larger clusters. This could be mitigated by setting a larger Prometheus instance type in the cortex cluster config.
