### ISSUE TITLE
Support AWS Session tokens as part of AWS Credentials

### ISSUE THREAD

**Issue by vishalbollu** [cortexlabs/cortex#741]
#### Description

Currently, Cortex only uses the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY for credentials. Add support for including AWS Session tokens.

#### Motivation
Users with MFA sessions are not able to use Cortex.

#### Additional context
- [ ] Operator can not rely on single-use tokens because they will expire, perhaps look into IAM roles and how to refresh session tokens.

**Comment by chrisranderson** [comment]
+1. Is there a way to get around this in the meantime, that doesn't involve creating a new user or changing permissions?

**Comment by deliahu** [comment]
@chrisranderson there is not currently a temporary way around this that I am aware of. Updating the CLI to support session tokens sounds like it would be straightforward, however the Cortex operator requires continued access to AWS, so it would have to implement logic to refresh session tokens when they expire. My understanding is the session tokens expire relatively quickly (based on a quick search 36 hours seems to be the max), and that the long-term credentials are required to refresh the token. If that's all true, it doesn't sound feasible to rely on session tokens in the operator.

That said, if it would be valuable to support session tokens only in the CLI (and not the operator), that is definitely something we can do. You would need to have access to the long-term credentials during cluster spin up, and thereafter the session token could be used to run all of the CLI commands. Would this address your concern?

**Comment by chrisranderson** [comment]
I'm brand new to Cortex - I just tried installing, couldn't, and found this issue. I don't know what the operator is, or know hardly anything about Cortex :) Maybe you could mention this issue in the error message if it will be a while before it is fixed.

My organization set the token expiration to 10 hours. My goal is to try Cortex out on a very short-term scale. If I have a good experience with it, I can probably request a new user / IAM role or whatever and avoid this problem entirely. For me, it doesn't matter if the cluster breaks at the 10 hour mark, as long as I can keep fiddling the next morning.

**Comment by deliahu** [comment]
@chrisranderson Yes, your use case makes sense since it's just to try out Cortex :)

Until we are able to add support for this, one potential work around for you to test out Cortex would be to ask your organization for a separate AWS account where you can have long-term credentials. Alternatively, you could use a personal account; as long as you spin down your cluster when you're done trying it out it won't be too expensive. Another option would be to ask for a set of long-term credentials in your organization, with the assumption that they can manually revoke them after 10 hours.

Do you think one of these options would work for you?

In the meantime, we will definitely improve that error message for the next release, thanks for bringing it to our attention!

**Comment by chrisranderson** [comment]
Those options will probably work. :) Thanks for the replies.
