### ISSUE TITLE
Is it possible to deploy to an existing K8 cluster? 

### ISSUE THREAD

**Issue by sebastianschramm** [cortexlabs/cortex#817]
Is it possible to deploy to an existing kubernetes cluster? The existing cluster can be on AWS EKS.

From the documentation it looks like that's currently not possible but I might have missed something.

**Comment by deliahu** [comment]
@sebastianschramm currently we do not support deploying to an existing Kubernetes cluster, however technically speaking I believe it could be supported somewhat easily. That said, there are some advantages with running a separate cluster for Cortex, which is why we decided to design it that way initially:

* Cortex requires a number of daemonsets to be running on the nodes, which could be intrusive for non-Cortex workloads (e.g. the Nvidia device plugin for GPUs, fluentd and cloudwatch for logging, the Istio CNI for networking, etc).
* Cortex supports fine grain cluster management, e.g. spot instances, instance types/distributions, etc (here are the docs for [cluster configuration](https://www.cortex.dev/cluster-management/config) and [spot instances](https://www.cortex.dev/cluster-management/spot-instances)). This should make it easy to configure the cluster tailored to the specific use case.
* Having a separate cluster helps with isolation, which can make some things more straightforward, like securing the cluster or tracking spend. It also helps ensure that other workloads don't interfere with Cortex, and vice versa.
* Since Cortex supports pod and node autoscaling, there shouldn't be much excess capacity on the cluster, so there shouldn't be too much overhead (I agree that the $0.10 per hour for EKS is a bit annoying, however depending on the size of your workload and you instance types this cost could be relatively small).

What is your motivation to install Cortex on an existing cluster?

**Comment by sebastianschramm** [comment]
@deliahu thank you very much for your detailed response. This answers my question and brings some additional details to my consideration that I was not aware of before.

I fully understand your design choices.The initial motivation for my question was to minimize excess capacity.

**Comment by deliahu** [comment]
Sounds good, feel free to reach out if you have any more questions!

**Comment by deliahu** [comment]
@sebastianschramm I just wanted to follow up on this thread, to say that we now support installing Cortex on an existing Kubernetes cluster (on AWS or GCP); here are the [docs](https://docs.cortex.dev/clusters/cortex-core-on-kubernetes/install).

**Comment by wilson-zimp** [comment]
@deliahu  - the link above for docs is not working (Feb 8,2021 comment). Can you please point me to the right documentation on how to install cortex on an existing Kubernetes cluster ? Thanks!

**Comment by deliahu** [comment]
@wilson-zimp thanks for reaching out. Support for installing Cortex on an existing cluster was removed in v0.30. We made this decision so that we can focus our efforts on improving the scalability, reliability, and security for Cortex on AWS; overall, we think Cortex can provide more value as a cloud-based service, where it can control cluster-related things such as node autoscaling, nodegroups, spot instances, auth, security, etc.

Are you able to create, or do you have access to an AWS account? Some of our users have had success with creating an AWS account dedicated to running Cortex (making inference requests from their backends on other clouds / on prem, or from clients directly, depending on the architecture and use case).

**Comment by wilson-zimp** [comment]
@deliahu - yes we have AWS eks cluster already deployed and we want to explore the option to deploy cortex to an existing EKS cluster and not the onprem kubernetes cluster. Please let me know if that not supported too.

**Comment by deliahu** [comment]
Cortex can only be run in a separate EKS cluster (it is also recommended to run Cortex in a dedicated VPC, which is the default behavior when a cluster is created). This is for many of the reasons I mentioned above: since Cortex has full control of the cluster, it can automate more tasks, e.g. node autoscaling, configuring nodegroups, installing GPU and/or Inferentia daemonsets, managing spot instances, validating resource capacity, etc.

What is the reason behind your preference to run it in your existing eks cluster?

**Comment by wilson-zimp** [comment]
We want to optimize cost by eliminating creation of additional LoadBalancers, NAT gateways and EKS cluster and also for ease of management. Thanks for answering my questions promptly, we will look into setting up a new EKS cluster if there isn't a way to reuse existing EKS cluster.

**Comment by deliahu** [comment]
Ok sounds good, feel free to reach out if you have additional questions! You can also reach us on our [community slack channel](https://community.cortex.dev/).
