### ISSUE TITLE
Tagging resources in AWS

### ISSUE THREAD

**Issue by adrianicv** [cortexlabs/cortex#854]
Is there a way to tag all the resources used in a Cortex cluster with the AWS tagging system?

Thank you in advance.

**Comment by vishalbollu** [comment]
@adrianicv Currently, there isn't a way to tag all of AWS resources created by Cortex. Why do you want to tag resources?

**Comment by adrianicv** [comment]
@vishalbollu In order to assign the clusters associated costs to different projects and use the AWS billing dashboard to explore the costs by project.

For example, if I have a project, called A, where I'm using a Cortex cluster and an API using API Gateway and Lambdas, and another project, called B, with a Cortex cluster and Cloudfront with a frontend interface hosted in S3. I want to be able to see the costs I have in project A and in project B independently. To accomplish this, I have a tag called Project and I assign the value A or B depending on the resource.

**Comment by deliahu** [comment]
@adrianicv yes, your use case makes sense, I've created issue https://github.com/cortexlabs/cortex/issues/856 to track this.

In the mean time, there may be a few existing tags you could use. The tag `alpha.eksctl.io/cluster-name` is set to the cluster name on all of the instances in the cluster. In addition, there is a tag for each cluster called `kubernetes.io/cluster/<cluster_name>` which has value `owned ` and is set on the load balancers in addition to the instances, so that should pick up more of the total cost of the cluster.

The main factor leading to cost differences between clusters is the cost of the instances, which should be captured with either of these tags.

Do these tags help provide a picture of your cluster cluster costs?

**Comment by adrianicv** [comment]
Thank you @deliahu.

Yes, for now, I'd could use these tags to identify cost and add them manually to the rest of the resources used in a project.

I close this question and I'll follow the issue opened.

**Comment by deliahu** [comment]
@adrianicv sounds good, thanks for bringing this to our attention.

**Comment by deliahu** [comment]
@adrianicv this has been released in v0.17.0 (here’s the full [changelog](https://github.com/cortexlabs/cortex/releases/tag/v0.17.0))

**Comment by adrianicv** [comment]
Thanks!!!!!
And thank you for this great tool!!!
