### ISSUE TITLE
Payload as bytes?

### ISSUE THREAD

**Issue by andriy-tsvikla** [cortexlabs/cortex#988]
Is there any way to receive payload from `def predict(self, payload):` as bytes? I am processing video in real time and i send frames to model as byte array. Converting image to base64 or just serializaing/deserializing array will take more time to process.

**Comment by RobertLucian** [comment]
@andriy-tsvikla at the moment, that's not possible. You still have to serialize your payload in order to be able to send it for inference. Will this be a blocker for you or are you okay with having it to serialize/deserialize the payload for the moment?

The situation won't stay this way too long. There's already a ticket on this matter. Check it out: https://github.com/cortexlabs/cortex/issues/917.

The silver lining here is that your API can respond with a bytes object instead. This means you won't have to deserialize on your client once you get the response. Check this out: https://github.com/cortexlabs/cortex/pull/915.

**Comment by andriy-tsvikla** [comment]
Thanks for clarification.
